FROM nvidia/cuda:12.3.1-devel-centos7 AS sdk

LABEL maintainer="bigdft-developers@lists.launchpad.net"

ENV DEBIAN_FRONTEND=noninteractive \
    LANG=C.UTF-8 \
    LANGUAGE=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    LD_LIBRARY_PATH=/usr/local/lib:/usr/local/cuda/lib64:${LD_LIBRARY_PATH} \
    LIBRARY_PATH=/usr/local/cuda/lib64:${LIBRARY_PATH} \
    NVIDIA_DRIVER_CAPABILITIES=compute,utility \
    NVIDIA_VISIBLE_DEVICES=all

SHELL ["/bin/bash", "-c"]

RUN useradd -ms /bin/bash lsim && \
    mkdir -p /etc/OpenCL/vendors && \
    echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd && \
    cp /usr/local/cuda/lib64/stubs/libcuda.so /usr/local/lib/libcuda.so.1 && \
    cp /usr/local/cuda/lib64/stubs/libnvidia-ml.so /usr/local/lib/libnvidia-ml.so.1 && \
    yum install -y epel-release && \
    yum install -y autoconf automake bison boost-devel boost-python3-devel bzip2 chrpath cmake cpio curl doxygen ethtool flex gdb gettext git glibc-devel gnome-common gobject-introspection-devel graphviz gtk-doc gtk3-devel intltool iproute kernel-headers kmod libarchive libmount-devel libnl3-devel libtool libtool-ltdl-devel libxml2-devel libyaml-devel lsof mesa-libGLU-devel net-tools netcdf-devel ninja-build numactl-libs ocl-icd openssh patch pciutils pcre-devel perl pkg-config redhat-lsb rsync strace swig tcl tk valgrind vim wget zeromq-devel zlib-devel && \
    yum install -y python3 python3-Cython python3-flake8 python3-ipython python3-matplotlib python3-numpy python3-pip python3-scipy python3-six python3-sphinx python3-sphinx-bootstrap-theme python3-sphinx_rtd_theme watchdog && \
    yum clean all && \
    rm -rf /var/cache/yum/*

EXPOSE 8888
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--NotebookApp.token=bigdft", "--no-browser"]

# Arm Allinea Studio
RUN mkdir -p /var/tmp && wget -q -nc --no-check-certificate -P /var/tmp https://developer.arm.com/-/media/Files/downloads/hpc/arm-allinea-studio/20-3/RHEL7/arm-compiler-for-linux_20.3_RHEL-7_aarch64.tar && \
    tar -x -f /var/tmp/arm-compiler-for-linux_20.3_RHEL-7_aarch64.tar -C /var/tmp && \
    cd /var/tmp/arm-compiler-for-linux_20.3_RHEL-7_aarch64 && \
    ./arm-compiler-for-linux_20.3_RHEL-7.sh --install-to /opt/arm --accept --only-install-microarchitectures=generic,thunderx2t99,generic-sve && \
    rm -rf /var/tmp/arm-compiler-for-linux_20.3_RHEL-7_aarch64.tar /var/tmp/arm-compiler-for-linux_20.3_RHEL-7_aarch64

ENV MODULEPATH=/opt/arm/modulefiles:$MODULEPATH \
    PATH=/opt/arm/arm-linux-compiler-20.3_Generic-AArch64_RHEL-7_aarch64-linux/bin/:$PATH \
    CC=armclang \
    CXX=armclang++ \
    F77=armflang \
    F90=armflang \
    FC=armflang \
    ARMPL=/opt/arm/armpl-20.3.0_Generic-AArch64_RHEL-7_arm-linux-compiler_aarch64-linux \
    LD_LIBRARY_PATH=/opt/arm/armpl-20.3.0_Generic-AArch64_RHEL-7_arm-linux-compiler_aarch64-linux/lib:$LD_LIBRARY_PATH \
    LIBRARY_PATH=/opt/arm/armpl-20.3.0_Generic-AArch64_RHEL-7_arm-linux-compiler_aarch64-linux/lib:$LIBRARY_PATH

# OpenMPI
RUN yum install -y bzip2 file hwloc make numactl-devel opens
