name: aiidalab
on: [push, workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-20.04
        if: "contains(github.event.head_commit.message, 'aiidalab') || github.event_name == 'workflow_dispatch'"
        steps:
        -   uses: actions/checkout@v2
        -   name: Login to DockerHub Registry
            run: echo Z+SX3uc7F3_MN8H | docker login -u rollanddoriandd@gmail.com --password-stdin
        -   name: Build the Docker image
            working-directory: aiidalab-sshonly
            run: docker build . --file Dockerfile --tag bigdft/aiidalab-docker:latest 
        -   name: Push the tagged Docker image
            run: |
                d=$(date +%Y-%m-%d--%H-%M-%S)
                docker tag bigdft/aiidalab-docker:latest bigdft/aiidalab-docker:$d
                docker push bigdft/aiidalab-docker:$d
                docker push bigdft/aiidalab-docker:latest
