name: sdk
on:
  push:
  workflow_dispatch:
    inputs:
      kind:
        description: 'type of launch'
        required: false
        default: 'manual'

jobs:
  build_sdk:
    strategy:
      matrix:
        mpi: [ompi]
        arch: [x86_64, arm, ppc64le]
        exclude:
          - mpi: mvapich
            arch: arm
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Get the tag and MPI version
        id: vars
        run: |
          source current_setup.sh
          echo ::set-output name=nompitag::$(echo ${BIGDFT_SYSTEM}${BIGDFT_SYSTEM_VERSION}_cuda${BIGDFT_CUDA_VERSION}_${{ matrix.arch }})
          if [ ${{ matrix.arch }} == "arm" ]; then
              echo ::set-output name=docker_platform::"linux/arm64"
          elif [ ${{ matrix.arch }} == "ppc64le" ]; then
              echo ::set-output name=docker_platform::"linux/ppc64le"
          else
              echo ::set-output name=docker_platform::"linux/amd64"
          fi
      - name: Build the tagged Docker image
        run: |
          docker buildx build --target sdk --platform ${{ steps.vars.outputs.docker_platform }} --file ./Dockerfiles/Dockerfile_sdk_${{ matrix.mpi }}_${{ matrix.arch }} --tag dorianalp38/sdk:${{steps.vars.outputs.nompitag}} --push .
      - name: Check if the image exists on Docker Hub
        run: docker pull dorianalp38/sdk:${{steps.vars.outputs.nompitag}}

          
  manifest:
        runs-on: ubuntu-20.04
        needs: build_sdk
        steps:
        -   uses: actions/checkout@v2
        -   name: Get the tag and MPI version
            id: vars
            run: |
                source current_setup.sh
                echo ::set-output name=tag::$(echo ${BIGDFT_SYSTEM}${BIGDFT_SYSTEM_VERSION}_cuda${BIGDFT_CUDA_VERSION})
        -   name: Login to DockerHub Registry
            run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        - name: Create and Push Multi-Arch Docker Manifest
          run: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker manifest create dorianalp38/sdk:centos7_cuda12.3.1 dorianalp38/sdk:centos7_cuda12.3.1_x86_64 dorianalp38/sdk:centos7_cuda12.3.1_arm dorianalp38/sdk:centos7_cuda12.3.1_ppc64le
            docker manifest annotate dorianalp38

               
               
