name: test_x86_64
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-20.04
    if: "contains(github.event.head_commit.message, 'x86_64') || github.event_name == 'workflow_dispatch'"
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Clean Up Before Install
        run: |
          sudo apt-get clean
          sudo apt-get autoremove
          docker system prune -a
          sudo rm -rf /var/lib/apt/lists/*
          sudo rm -rf /tmp/*
          df -h
      - name: Build the Docker image
        working-directory: Dockerfiles
        run: docker build --file Dockerfile_sdk_ompi_x86_64 --tag dorianalp38/sdk:ompi_x86_64 .
      - name: Push the tagged Docker image
        run: |
          d=$(date +%Y-%m-%d--%H-%M-%S)
          docker tag dorianalp38/sdk:ompi_x86_64 dorianalp38/sdk:$d
          docker push dorianalp38/sdk:$d
          docker push dorianalp38/sdk:ompi_x86_64
